# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('travel_sdate', models.DateTimeField()),
                ('travel_edate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_creator', to='logreg.User')),
                ('trip_travelers', models.ManyToManyField(related_name='trip_travelers', to='logreg.User')),
            ],
        ),
    ]
